# Generated by Django 3.0.4 on 2020-03-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='title',
            new_name='name',
        ),
    ]
